### ISSUE TITLE
Enhancement: Let background bars represent time fraction

### ISSUE THREAD

**Issue by steven2358** [navjagpal/browser-timetracker#16]
Make the blue bar background behind each site in the popup not 100% long but just x% long (horizontally) where x is the percentage spent on that site. All rows together will form a nice diagram that way.

Since the most visited site will typically be something like 25%, the diagram may appear too narrow. Possible solution: widen all bars by a constant factor, e.g. so as to make the first bar full-width. See image.

![bar_diagram](https://cloud.githubusercontent.com/assets/164072/10736558/f6df2a48-7c0d-11e5-8599-48db1cd2c90a.png)

**Comment by navjagpal** [comment]
Here's a link that may help with the implementation: http://stackoverflow.com/questions/12021233/css-to-set-the-background-color-for-just-a-percentage-of-the-width-of-a-table-ro
